import Head from "next/head";
import Link from "next/link";
import { sanityClient, urlFor } from "../sanity";
import { GetServerSideProps } from "next";
import { Collection } from "../typings";

interface Props {
  collections: Collection[];
}

const Home = ({ collections }: Props) => {
  return (
    <div className="max-w-7xl mx-auto flex-col min-h-screen py-20 px-10 2xl:px-0">
      <Head>
        <title>NFT DROP</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/NFT_Icon.png/600px-NFT_Icon.png"
        />
      </Head>

      <h1 className="mb-10 text-4xl font-extralight">
        THE
        <span className="font-extrabold underline decoration-pink-600/50">
          {" "}
          PLUTO{" "}
        </span>
        NFT MARKET PLACE
      </h1>

      <main className="bg-scale-100 p-10 shadow-xl shadow-rose-400">
        <div
          className="grid space-x-3 md:grid-cols-2
        lg:grid-cols-3 2xl:grid-cols-4"
        >
          {collections &&
            collections.map((collection) => (
              <Link href={`/nft/${collection.slug.current}`}>
                <div
                  className="flex flex-col items-center cursor-pointer
        transition-all duration-200 hover:scale-105"
                >
                  <img
                    draggable="false"
                    className="h-96 w-60 rounded-2xl object-cover"
                    src={urlFor(collection.mainImage).url()}
                    alt=""
                  />

                  <div className="p-5">
                    <h2 className="text-3xl">{collection.title}</h2>
                    <p className="mt-2 text-sm text-gray-400">
                      {collection.description}
                    </p>
                  </div>
                </div>
              </Link>
            ))}
        </div>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const query = `*[_type == "collection"] {
	_id,
	title,
	address,
	description,
  nftCollectionName,
	mainImage{
		asset
	},
	previewImage{
		asset
	},
	slug {
		current
	},
	creator-> {
		_id,
		name,
		address,
		slug {
			current
		},
	}
}`;
  const collections = await sanityClient.fetch(query);

  return {
    props: {
      collections,
    },
  };
};

// import Head from "next/head";
// import Link from "next/link";
// import { sanityClient, urlFor } from "../sanity"
// import { GetServerSideProps } from 'next'
// import { Collection } from '../typings'

// interface Props {
//     collections: Collection[]
// }

// const Home = ({ collections }: Props) => {

//     return (
//         <div className="max-w-7xl mx-auto flex-col min-h-screen py-20 px-10 2xl:px-0">
//             <Head>
//                 <title>NFT DROP</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/NFT_Icon.png/600px-NFT_Icon.png" />
//             </Head>

//             <h1 className="mb-10 text-4xl font-extralight">
//                 THE
//                 <span className="font-extrabold underline decoration-pink-600/50">
//                     {" "}
//                     PLUTO{" "}
//                 </span>
//                 NFT MARKET PLACE
//             </h1>

//             <main className="bg-scale-100 p-10 shadow-xl shadow-rose-400">
//             <div
//                     className="grid space-x-3 md:grid-cols-2
//         lg:grid-cols-3 2xl:grid-cols-4"
//                 >

//                         <Link href="/nft/megami-nft">
//                             <div
//                                 className="flex flex-col items-center cursor-pointer
//         transition-all duration-200 hover:scale-105"
//                             >
//                                 <img
//                                     className="h-96 w-60 rounded-2xl object-cover"
//                                     src="https://cdn.sanity.io/images/tcbt8p2d/production/f9b38e911a22377a157173b13b8fc6ee971cebf7-600x626.gif"
//                                     alt=""
//                                 />
//                                 <div className="p-5">
//                                     <h2 className="text-3xl">
//                                     MEGAMI NFT
//                                     </h2>
//                                     <p className="mt-2 text-sm text-gray-400">
//                                     Naoki Saito's 1/1 quality as an NFT collectible. This is the concept of MEGAMI. Your own Megami, not for anyone else. The Megami of your choice will empower you. Find your own personal Megami and rediscover your own value.
//                                     </p>
//                                 </div>
//                             </div>
//                         </Link>
//                         <Link href="/nft/bored-ape">
//                             <div
//                                 className="flex flex-col items-center cursor-pointer
//         transition-all duration-200 hover:scale-105"
//                             >
//                                 <img
//                                     className="h-96 w-60 rounded-2xl object-cover"
//                                     src="https://cdn.sanity.io/images/tcbt8p2d/production/8f6d1b95c522459c44481a0d831487898d87c919-498x498.gif"
//                                     alt=""
//                                 />
//                                 <div className="p-5">
//                                     <h2 className="text-3xl">
//                                     BORED APE
//                                     </h2>
//                                     <p className="mt-2 text-sm text-gray-400">
//                                     The Bored Ape  is a collection of unique Bored Ape NFTs— unique digital collectibles living on the Ethereum blockchain.
//                                     </p>
//                                 </div>
//                             </div>
//                         </Link>
//                         <Link href="/nft/redacted-remilio-babies">
//                             <div
//                                 className="flex flex-col items-center cursor-pointer
//         transition-all duration-200 hover:scale-105"
//                             >
//                                 <img
//                                     className="h-96 w-60 rounded-2xl object-cover"
//                                     src="https://cdn.sanity.io/images/tcbt8p2d/production/b5f30ed4aa535e080c979bd7d2407d3e93dda0c4-407x413.gif"
//                                     alt=""
//                                 />
//                                 <div className="p-5">
//                                     <h2 className="text-3xl">
//                                     REDACTED REMILIO BABIES
//                                     </h2>
//                                     <p className="mt-2 text-sm text-gray-400">
//                                     Redacted Remilio Babies is a collection of neochibi pfp NFT's expanding the Milady Maker paradigm with the introduction of young J.I.T. energy and schizophrenic reactionary aesthetics. We are #REMILIONAIREs.
//                                     </p>
//                                 </div>
//                             </div>
//                         </Link>
//                         <Link href="/nft/lets-walk">
//                             <div
//                                 className="flex flex-col items-center cursor-pointer
//         transition-all duration-200 hover:scale-105"
//                             >
//                                 <img
//                                     className="h-96 w-60 rounded-2xl object-cover"
//                                     src="https://cdn.sanity.io/images/tcbt8p2d/production/000db9bb0d7a10346f0e0bde2572005c0fe2d025-250x250.gif"
//                                     alt=""
//                                 />
//                                 <div className="p-5">
//                                     <h2 className="text-3xl">
//                                     LETS WALK
//                                     </h2>
//                                     <p className="mt-2 text-sm text-gray-400">
//                                     First ever 'Walking' NFT collection LetsWalk
//                                     </p>
//                                 </div>
//                             </div>
//                         </Link>
//                 </div>
//             </main>
//         </div>
//     );
// };

// export default Home;
